### ISSUE TITLE
solicit abstracts for TDWG 2017 Symposium on Biological Interaction Data - towards data standardization

### ISSUE THREAD

**Issue by jhpoelen** [BioComp-USP/interaction-data-group#10]
Perhaps a bit late with a deadline of 21 July 2017 for TDWG 2017 Symposium on Interaction Data (see https://tdwg.github.io/conferences/2017/ and https://tdwg.github.io/conferences/2017/program/abstract/?id=1lof4zPCG2_NqaYOsg59G5o2UmuJ6h9pABgQYrC5aITE ) ... but would it be an idea to invite others to submit an abstract to TDWG 2017, or at least tell others about it?

Active species interaction projects / thinkers that I can think of now are:

1. Natural History Museum, London, Interaction Bank - Vince Smith, Ed Baker @edwbaker. 
1. Avian Diet Database - Allen Hurlbert @ahhurlbert
1. GoMexSI - James Simons @jsimons9
1. Web of Life - Jordi Bascompte et al.
1. mangal.io - @tpoisot 
1. useful rants, utopic visions and insights by @rdmpage 

Please feel free to add to the list in comments below. 

Apologies in advance for undesired @ spam - please let me know if it bother you.

**Comment by saraiva-usp** [comment]
Hi Jorrit, 
I think it is worth sending those people a message. Can you do that by any means? 
As a last resource we may try and get a few more days to receive their contributions. It worked when we used the old TDWG system; not sure how flexible it will be with the new one from Pensoft.
Antonio

**Comment by tpoisot** [comment]
Funny how things work -- I spent the day working with @SteveViss (our eco-informatician) on the v2 or mangal, which we hope to release in september. It will be a quite major update, with a much better data format, and some extended support for geospatial data (we already mirror web of life, for the record), as well as (a few months later) integration with AI/machine learning methods to infer missing interactions.

I can write an abstract before the deadline explaining the data format, what considerations about ecology we had when designing it, and how it can easily be adopted by other projects (this would make querying interactions data orders of magnitude less painful than it is now). I was considering attending the meeting anyways, since it is in Ottawa. I can also showcase some of our current research activities made possible by mangal (and GLOBI, hi @jhpoelen !).

Do you think this is interesting?

If we also have a critical mass of people here, I think it would be wise to set aside a few hours to hack together something to easily convert from/to the various formats, because we will need to integrate these different databases at some point.

**Comment by ahhurlbert** [comment]
This sounds like a great meeting, but unfortunately I won't be able to make it.

FYI, I hope to submit the [Avian Diet Database](https://github.com/hurlbertlab/dietdatabase) for publication in the next month or so. I might ask any interested parties here (@jhpoelen, others) for feedback...

**Comment by edwbaker** [comment]
Vince and I won't be at TDWG this year - we could send a poster describing our work with the NHM contingent though?

**Comment by jhpoelen** [comment]
@tpoisot to me, an abstract that includes the data format, adoption model and history of the project of mangal.io is interesting . . . but hey, I am not the organizer ; )

@ahhurlbert looking forward to the the Avian Diet Database publication. Can I persuade you to use the github release mechanism and integration with Zenodo to publish a publishable version? This way, GloBI will automatically pick up the released version instead of the work in progress.

@edwbaker to me a poster presence sounds interesting, but again, I am not organizing the symposium. I was wondering whether there a way to do a remote presentation. . . would that work for you?

**Comment by jhpoelen** [comment]
@saraiva-usp are remote presentations accepted for symposium . . . I imagine that this might be a little more inclusive . . .

**Comment by jhpoelen** [comment]
For resulting submitted abstracts for TDWG 2017 - see 
https://tdwgproceedings.pensoft.net/browse_user_collection_documents?collection_id=47
